version: '3'
services:
      web:
              image: holy-unblocker
              build: .
              ports:
                      - "8080:8080" # Set first port to whatever you want, linking it with whatever            
